import csv
from dronekit import LocationGlobalRelative, LocationGlobal, LocationLocal

"""
This is the log analyzer tool build to comb a csv file generated by a drone.

Author: Joseph Schwalb
"""

class LogAnalyzer():


    def __init__(self, some_file):
        self.some_file = some_file

        self.time_start = None
        self.time_total = None



        with open(some_file, 'r') as csv_file:
            reader = csv.reader(csv_file)
            for idx, field in enumerate(reader):
                if idx == 0:
                    self.time_start = float(field[0])
                    print('0')
                else:
                    dt = float(field[0]) - self.time_start
                    self.time_total = dt
                    print(self.time_total)


        """
        Begin declaration of the all state variables for later analysis.
        """

    def replay_log(self):
        start_time = csv

    def detect_collision(self):
        pass

logAnalyzer = LogAnalyzer('drone1_csv')
